### ISSUE TITLE
Cannot find module './xPathParser.raw' 

### ISSUE THREAD

**Issue by PolyDevil** [FontoXML/fontoxpath#112]
I cloned the repository, tried to run `npm start` and `npm run test` and got the same error:
`Error: Cannot find module './xPathParser.raw'`;

There is a line in `.gitignore`:
https://github.com/FontoXML/fontoxpath/blob/39c7039bb4dd0883170b98eca225f6c4e619c78b/.gitignore#L9

Clearly, `src/parsing` doesn't contain any file with that name:
https://github.com/FontoXML/fontoxpath/tree/39c7039bb4dd0883170b98eca225f6c4e619c78b/src/parsing

I guess it is some typescript code that should be compiled to `xPathParser.raw`.
But it doesn't exist in the repository.

Where can I find it?

**Comment by DrRataplan** [comment]
Hi PolyDevil,

The `xPathParser.raw` file is indeed a compiled file that is not checked in. It's compiled from the `.pegjs` file that resides somewhere in the same folder. The `xPathParser.raw` file is generated in a `postInstall` hook when you run `npm install`. Did you already do an `npm install`?

Regards,

Martin

**Comment by PolyDevil** [comment]
I did. There was an issue with `java`.
I didnt had it installed and got an error during the `npm build`.
Similar to https://github.com/google/closure-compiler-js/issues/67.
