### ISSUE TITLE
Filter expression is not executed on array constructor in some cases

### ISSUE THREAD

**Issue by JosVerburg** [FontoXML/fontoxpath#116]
Repro case:
```xquery
[xml]!.(1)/title
```

These give the same result but do not error as they are wrapped in extra expression.
```xquery
([xml]!.(1))/title
[xml]!.(1)!./title
```

**Comment by DrRataplan** [comment]
It seems that the rewrapping code in the parser is not behaving correctly. I think the bug may be here: https://github.com/FontoXML/fontoxpath/blob/master/src/parsing/xpath.pegjs#L675

I'm unsure what the excact issue is though.

**Comment by JosVerburg** [comment]
Wrapping seems to be related to it, I seem to have encountered it again in the tests Lookup-023 and UnaryLookup-023 in which the XQueryX format expect 2 simpleMapExpr to be nested, we however only have one with 3 pathExpr childs.

**Comment by DrRataplan** [comment]
I can no longer reproduce this bug. I'm closing it.

For the record, tried to repro it like this: https://xpath.playground.fontoxml.com/?state=H4sIAJyJPGIAA21RwU7DMAz9FZPLQJo6uE6lEvchAQJpCDhkrbtGJHGVOFOraf%2BO0zLtAFKkvMTPz8%2F2UTlqUK1vl%2Bqgg9E7i1Gt1fGklmpwVmApV%2FXpAUo2bLEaes1d0Vs97gMl3xQteSYhFTW5cjWTJn5MzukwVq%2BdiSBHg0UdvPF7YCILLQXYPm6WsH0SSdC%2Bge1zwjAW5eqc%2B1u4jxOaMZjmfoGN4UX1Tglq7SG%2FAA%2BSy13WJw%2FcodRrOVvq%2F2QP2vXS6kVB1zXGCI4CwjkKbSAnth36BGaWZOohmH33v26PwWlr%2FPeievAk%2FAC7xDzbEWWLHGGUkrHT8hQUgDEypJhti4%2B3l81FeUK59XKVt5B3Mg1I1vIhH19XxfXdzTxyidWyCBz4zFCnH6ftx9LdAQAA
