### ISSUE TITLE
FontoXPath types are not completely compatible with lib.dom types

### ISSUE THREAD

**Issue by mehmetscoskun** [FontoXML/fontoxpath#122]
For example while `namespace` of `Attr` might be `string` or `null` in lib.dom, in FontoXPath it can only be `string`. It causes some incompatibility issues. Probably there are more.

**Comment by JosVerburg** [comment]
The cases we've seen so far are `Attr.namespaceURI` and `Attr.prefix` which are of type `string` but from lib.dom we got `string | null`.

**Comment by bwrrp** [comment]
`string | null` is the correct type. The DOM methods that create Attr nodes accept both null and the empty string to signify the absence of a namespace or prefix, but these properties will always end up as null in both cases.
