### ISSUE TITLE
Error when iterating and comparing over empty tuples

### ISSUE THREAD

**Issue by JCEntrena** [FontoXML/fontoxpath#160]
When we check a condition over the elements of two different tuples, if one of them is empty, the comparison raises an error, because no element has been picked from the empty tuple.

Repro case: 

`some $x in (1,2,3), $y in () satisfies ($x eq $y)`

Can be checked on Fonto XPath Playground. 

This error is occurring on one of the FLWOR tests, inside a where clause, causing it to fail. In order to run the FLWOR tests successfully, this test will be disabled until the error is solved.

**Comment by DrRataplan** [comment]
Fixed by #179
