### ISSUE TITLE
memory leak in nodeValueCache

### ISSUE THREAD

**Issue by DrRataplan** [FontoXML/fontoxpath#17]
The nodeValueCache.js files mentions why weak maps are a great choice for what we're doing there, but a normal map is used.

This causes a memory leak when one is working with loads of nodes with different lifetimes than the application...

**Comment by DrRataplan** [comment]
Fixed by 51be4aff307b7b5035d341b296158bb6cc87127c

**Comment by wvbe** [comment]
Confirmed! 👏
