### ISSUE TITLE
Using /. to sort sequence produced by preceding-sibling yields incorrect result

### ISSUE THREAD

**Issue by ThomasGravekamp** [FontoXML/fontoxpath#18]
Example XML:
```
<xml>
  <node1></node1>
  <node2></node2>
  <node3></node3>
</xml>
```

Example XPath:
```
(//node3/preceding-sibling::*)/.
```

Expected result: `<node1 /><node2 />`
Actual result: `<node2 /><node1 />`

**Comment by DrRataplan** [comment]
This is caused by the preceding-sibling selector having the wrong result ordering metadata set.

I'll fix it and create a new release
