### ISSUE TITLE
Request for fn:matches

### ISSUE THREAD

**Issue by QAnders** [FontoXML/fontoxpath#188]
Hi, thanks som much for your hard work!
Any possibility to share a "roadmap" for fn:matches function?

Please see https://github.com/wvbe/node-schematron/issues/1#issuecomment-557182541 for use-case... :)

**Comment by wvbe** [comment]
I would like to add that `fn:substring` and `fn:string-to-codepoints` are other XPath functions currently not supported in `fontoxpath`, but used in the schematron file for which wvbe/node-schematron#1 was reported.

**Comment by JosVerburg** [comment]
We indeed do not yet support `fn:matches` but we `fn:substring` and `fn:string-to-codepoints` are implemented. @wvbe updating to the latest version should resolve those 2.

I'll take a closer look at matches to see if we can get that in sometime soon.

**Comment by DrRataplan** [comment]
The main historical problem with matches, and xs:patterns in general were the differences between JS regexes and xs:pattern. Recently though, https://github.com/bwrrp/xspattern.js was released. 

Looking at the [documentation of fn:matches](https://www.w3.org/TR/xpath-functions-31/#func-matches), there is no replace yet, nor are there capture groups or backreferences (the point where XPath's xs:pattern deviates from the XSD xs:pattern), we should be able to implement it using that library.

I can not promise it will be implemented soon, but I'll take a look on how we can implement it! fn:matches has been on my wishlist for a while too!

**Comment by DrRataplan** [comment]
I took some time to work on this, and I found the following:

 - It was a bit of a hassle to properly inject the xs pattern library into FontoXPath, but I found a way, see the #189 PR for the implementation
 - While on first sight, [xspattern.js](https://github.com/bwrrp/xspattern.js) seems to be usable for `fn:matches`, there are some complications. Mainly the substring behaviour of fn:matches versus the full match behaviour of 'normal' patterns is a nasty difference. I filed an issue (https://github.com/bwrrp/xspattern.js/issues/9) to see whether and how we can make xspattern.js work for this use-case.

We'll track progress right here in this issue!

**Comment by DrRataplan** [comment]
I have made a PR on xspattern.js which implements basic pattern support for `fn:matches`. This will cover everything that's needed for the schematron files referenced in the issue @QAnders made in @wvbe's schematron implementation. I believe those schematron rules only use 'simple' patterns: no backreferences, no flags, etcetera.

However, before integrating everything, I would at least like to be able to recognize everything that we do not yet support, and throw appropriate errors. For example, using backreferences in `fn:matches` should not act like the pattern contains a syntax error, but indicate that we do not support those yet.

**Comment by DrRataplan** [comment]
I made another PR on xspattern.js that covers the additional functionality: https://github.com/bwrrp/xspattern.js/pull/13 If that one is done, expect a release here!

**Comment by DrRataplan** [comment]
A small update, I ran into various issues while getting matches injected. I'm expecting to work on that next week

**Comment by DrRataplan** [comment]
Good news! we managed to make it work! I'll publish this all this afternoon! Please get back to us if you have any feedback!

**Comment by DrRataplan** [comment]
FontoXPath 3.12.0 is a fact! Closing this issue
