### ISSUE TITLE
Attribute nodes can not be replaced by using the replace expression 

### ISSUE THREAD

**Issue by ThomasGravekamp** [FontoXML/fontoxpath#196]
Attribute nodes can not be replaced by using the XQuery Update Facility [replace expression](https://www.w3.org/TR/xquery-update-30/#id-replace). It throws an error: `Error: XUDY0009: The target undefined for replacing a node must have a parent.`.

This behaviour can be reproduced using the [playground](https://xpath.playground.fontoxml.com/?mode=2&variables=%7B%7D&xml=%3Cxml%3E%0A++%3Ctitle%3Expath.playground.fontoxml.com%3C%2Ftitle%3E%0A++%3Csummary%3EThis+is+a+learning+tool+for+XML%2C+XPath+and+XQuery.%3C%2Fsummary%3E%0A++%3Ctips%3E%0A++++%3Ctip+id%3D%27edit%27%3EYou+can+edit+everything+on+the+left%3C%2Ftip%3E%0A++++%3Ctip+id%3D%27examples%27%3EYou+can+access+more+examples+from+a+menu+in+the+top+right%3C%2Ftip%3E%0A++++%3Ctip+id%3D%27permalink%27%3EAnother+button+there+lets+you+share+your+test+using+an+URL%3C%2Ftip%3E%0A++%3C%2Ftips%3E%0A%3C%2Fxml%3E&xpath=replace+node+%40id+with+attribute+%7B%22id%22%7D+%7B%22value%22%7D&context=%2F%2Ftip%5B%40id%3D%22examples%22%5D).

**Comment by DrRataplan** [comment]
You're on a roll! I think we overlooked attributed when implementing this. Would you feel confident in fixing this? There should be a number of QT3 tests that will cover replacing attributes!

**Comment by DrRataplan** [comment]
Turns out this was only an issue in the playground! Same as the last one you filed. We've already fixed it!
