### ISSUE TITLE
wrong results when using xpath with attributes

### ISSUE THREAD

**Issue by mygithub-user** [FontoXML/fontoxpath#21]
Hello,
In order to try fontoxpath, I created a small test.
The results were not as expected, though they were correct at the Demo page.
The xpath should return all Icons which do not have a tooltip. The expected results here is to get 3 of the Icons (all, but the first one which has a tooltip with value 'test') , but instead all Icons are returned.
I would appreciate your analysis. following is the mocha test.

Thanks,
Gaia

var fontoxpath = require('fontoxpath');
var domParser = require('xmldom').DOMParser;
var assert = require('assert');

describe("fontoxpath functionallity", function() {
    it('icons with not tooltip', function() {
        var xpath_str = "//core:Icon[(not(@tooltip) or normalize-space(@tooltip)='')]";
        var xml_str = "<TEST xmlns:core=\"a.b.core\">" +
            "<core:Icon tooltip=\"test\"></core:Icon>\n" +
            "<core:Icon ></core:Icon>\n" +
            "<core:Icon tooltip=\" \"></core:Icon>\n" +
            "<core:Icon tooltip=\"\"></core:Icon>\n" +
            "</TEST>"
        var parser = new domParser();
        var document = parser.parseFromString(xml_str);

        var nodes = fontoxpath.evaluateXPathToNodes(xpath_str, document, fontoxpath.domFacade, null, {namespaceResolver: function (prefix)
            {
                var NAMESPACES = {
                    "core": "a.b.core"
                };
                return NAMESPACES[prefix];
            }});
        assert.ok(nodes.length === 3, "expected 3 got " + nodes.length);//result is 4
    });
});

**Comment by DrRataplan** [comment]
Hi Gaia,

Thanks for the feedback! XPath is case-sensitive, so it is correct that an XPath searching for attributes named 'ToolTip' (upper case T) does not match 'tooltip' (lower case t). Could you check the casing? When I write it like this, it works: [playground](https://xpath.playground.fontoxml.com/?xml=%3CTEST+xmlns%3Acore%3D%22a.b.core%22%3E%0A%22%3Ccore%3AIcon+tooltip%3D%22test%22%3E%3C%2Fcore%3AIcon%3E%0A%22%3Ccore%3AIcon+%3E%3C%2Fcore%3AIcon%3E%0A%22%3Ccore%3AIcon+tooltip%3D%22+%22%3E%3C%2Fcore%3AIcon%3E%0A%22%3Ccore%3AIcon+tooltip%3D%22%22%3E%3C%2Fcore%3AIcon%3E%0A++%3C%2FTEST%3E&xpath=%2F%2Fcore%3AIcon%5B%28not%28%40tooltip%29+or+normalize-space%28%40tooltip%29%3D%27%27%29%5D).

I do know of some issues regarding xmldom  (https://github.com/jindw/xmldom/issues/213). I can recommend slimdom.js (https://github.com/bwrrp/slimdom.js). Though it does not contain a parser,  someone has written one as an additional package.

**Comment by mygithub-user** [comment]
I did use lower case, It seems there was some auto fix when I copied it :)
I will try slimdom and it's parser ... thanks

**Comment by mygithub-user** [comment]
With slimdom it works well, Thanks

**Comment by DrRataplan** [comment]
Hy,

I took some time to look into this further, turns out xmldom sets the namespaceURI property of attributes in the null namespace to undefined (see https://runkit.com/embed/1r0orbj9ki0k). It should be null, I do not think FontoXPath is the place to 'fix' this behaviour.

Again, thanks for the feedback!

**Comment by mygithub-user** [comment]
Thank a lot! Indeed when fixing it, FontoXPath works as expected.
I will try to propose a fix for xmldom.
