### ISSUE TITLE
array:sort does not sort array with sequence members properly

### ISSUE THREAD

**Issue by mehmetscoskun** [FontoXML/fontoxpath#211]
array:sort([(1,0), (1,1), (0,1), (0,0)]) should return [(0,0), (0,1), (1,0), (1,1)] but does not.

**Comment by DrRataplan** [comment]
Ay, too bad. Could you tell us what it does return and how you are running the XPath?

In the playground, I'm getting this: https://xpath.playground.fontoxml.com/?mode=0&variables=%7B%7D&xml=%3Cxml%2F%3E&xpath=array%3Asort%28%5B%281%2C0%29%2C+%281%2C1%29%2C+%280%2C1%29%2C+%280%2C0%29%5D%29+%3D%3E+array%3Afor-each%28string-join%28%3F%2C+%27%2C%27%29+%29&context=

in: `array:sort([(1,0), (1,1), (0,1), (0,0)]) => array:for-each(string-join(?, ',') )`
out: 
```
Array with 4 items:
"0,0"
"0,1"
"1,1"
"1,0"
```

**Comment by mehmetscoskun** [comment]
`array:flatten(array:sort([(1,0), (1,1), (0,1), (0,0)]))` is also an option to log it.
