### ISSUE TITLE
Build FontoXPath as a module

### ISSUE THREAD

**Issue by DrRataplan** [FontoXML/fontoxpath#221]
Currently, FontoXPath builds an UMD module, but in order to include it without using those pesky build tools in a more modern environment, a `.mjs` could make things easier.

**Comment by JoernT** [comment]
yes! That would erase a build step for me. In web components world you usually deal with ES6 modules and it has become the standard.

Our goal is to go buildless and use http2 instead (it's about time).

**Comment by DrRataplan** [comment]
PR is at #250

**Comment by JoernT** [comment]
clap clap clap! this is huge.
