### ISSUE TITLE
prod-ValueComp~value-comparison-12 is failing when 'alltests' is run

### ISSUE THREAD

**Issue by mehmetscoskun** [FontoXML/fontoxpath#240]
When I run `npm run qt3tests` or `npm run qt3testsxqueryx`, I do not see this failure but when `npm run alltests` is run, `prod-ValueComp~value-comparison-12` is failing.

**Comment by DrRataplan** [comment]
It must be this test:
```
	before(() => {
		registerCustomXPathFunction(
			'test:custom-function1',
			['xs:string?'],
			'xs:boolean',
			function (dynamicContext, string) {
				chai.assert.isOk(dynamicContext, 'A dynamic context has not been passed');
				chai.assert.isOk(dynamicContext.domFacade, 'A domFacade has not been passed');
				return string === null || string === 'test';
			}
		);
```
and in registerCustomXPathFunction:
```

	const [prefix, localName] = parts;
	let namespaceURIForPrefix = staticallyKnownNamespaceByPrefix[prefix];
	if (!namespaceURIForPrefix) {
		namespaceURIForPrefix = `generated_namespace_uri_${prefix}`;
		registerStaticallyKnownNamespace(prefix, namespaceURIForPrefix);
	}
```

This causes the 'test' namespace uri to be registered globally. For now, I'll edit the test on our side and add this to the list of things that are going to break when we release 4.0

**Comment by JosVerburg** [comment]
@DrRataplan do we have a tracking issue with breaking changes for 4.0?
Might be good to have this publicly available to make future upgrades easier.
