### ISSUE TITLE
XQuery Update Facility

### ISSUE THREAD

**Issue by st-alpers** [FontoXML/fontoxpath#254]
Hi there. I'm thinking to use XQuery Update Facility but on npmjs.com it says this is in preview and subject to change. Do you recommend using it in a production environment?

**Comment by DrRataplan** [comment]
Hello there!

The reason why we stated that XQUF was in preview is that we did not want
to tie ourselves down at the moment to the API shape and at the time we had
really barebones support for XQUF. That shape may still change somewhere in
the future but will be regarded as a breaking change, same as the other
APIs offered in FontoXPath.

To answer your question, I would use the XQUF features in FontoXPath in
production. For reference, our main product (the Fonto editor) has been
using it for quite some time now, allowing third parties to write their own
scripts and it has proven to be stable.

If you have any feedback to us regarding XQUF or FontoXPath in general,
don't hesitate to reach out! We are always happy to help!

I'll leave this issue open as a reminder to remove that confusing comment
on npm. Thanks for highlighting it to us.
