### ISSUE TITLE
compareSpecificity returning unexpected answer

### ISSUE THREAD

**Issue by wvbe** [FontoXML/fontoxpath#258]
(Seen in fontoxpath@3.9.2 and 3.12.0)

Hey guys, I was experiencing some unexpected behaviour in the `xml-renderer` lib. That module uses fontoxpath's `compareSpecificity` to select the best-matching rendering rule for a given node. As a perceived bug, suddenly the selector `self::type[parent::*]` no longer "won" from `self::type` because it is not perceived more specific.

In NodeJS I tested the outcomes of `compareSpecificity` and I _think_ I've found something unexpected.

```
> const fontoxpath = require('fontoxpath')
undefined
> fontoxpath.compareSpecificity('self::type', 'self::type[parent::*]')
0
```

`-1` was expected because the selector "must be of type element, with node name 'type', and must have a parent" is more specific than just "must be of type element, with node name 'type'".

In the same train of thought, a different predicate _did_ yield the expected result:
```
> fontoxpath.compareSpecificity('self::type', 'self::type[not(parent::*)]')
-1
```

As well as
```
> fontoxpath.compareSpecificity('self::type', 'self::type[parent::nerf]')
-1
```

I feel as though I must be missing something here!

**Comment by wvbe** [comment]
As a workaround I can use `self::type[parent::element()]` instead of `self::type[parent::*]`! This is not an urgent issue but I did want to either check my own understanding or highlight a possible bug to you :) Thanks

**Comment by DrRataplan** [comment]
Great find! Error is in NameTest.ts, seems like we do not set any
specificity when the selector is of the form '*'. The form 'element(*)' and
the form 'attribute(*)' do get a specificity. That check there around line
24 does not make sense.

Op do 2 jul. 2020 om 21:49 schreef Wybe <notifications@github.com>:
