### ISSUE TITLE
casting attribute to string does not work on the XPath playground

### ISSUE THREAD

**Issue by mehmetscoskun** [FontoXML/fontoxpath#262]
[One example](https://xpath.playground.fontoxml.com/?mode=0&variables=%7B%7D&xml=%3Cxml%3E%0A++%3Ctitle%3Expath.playground.fontoxml.com%3C%2Ftitle%3E%0A++%3Csummary%3EThis+is+a+learning+tool+for+XML%2C+XPath+and+XQuery.%3C%2Fsummary%3E%0A++%3Ctips%3E%0A++++%3Ctip+id%3D%27edit%27%3EYou+can+edit+everything+on+the+left%3C%2Ftip%3E%0A++++%3Ctip+id%3D%27examples%27%3EYou+can+access+more+examples+from+a+menu+in+the+top+right%3C%2Ftip%3E%0A++++%3Ctip+id%3D%27permalink%27%3EAnother+button+there+lets+you+share+your+test+using+an+URL%3C%2Ftip%3E%0A++%3C%2Ftips%3E%0A%3C%2Fxml%3E&xpath=%2F%2Ftip%5B%40id%3D%27edit%27%5D&context=)

[Another example](https://xpath.playground.fontoxml.com/?mode=0&variables=%7B%7D&xml=%3Cxml%3E%0A++%3Ctitle%3Expath.playground.fontoxml.com%3C%2Ftitle%3E%0A++%3Csummary%3EThis+is+a+learning+tool+for+XML%2C+XPath+and+XQuery.%3C%2Fsummary%3E%0A++%3Ctips%3E%0A++++%3Ctip+id%3D%27edit%27%3EYou+can+edit+everything+on+the+left%3C%2Ftip%3E%0A++++%3Ctip+id%3D%27examples%27%3EYou+can+access+more+examples+from+a+menu+in+the+top+right%3C%2Ftip%3E%0A++++%3Ctip+id%3D%27permalink%27%3EAnother+button+there+lets+you+share+your+test+using+an+URL%3C%2Ftip%3E%0A++%3C%2Ftips%3E%0A%3C%2Fxml%3E&xpath=string%28.%2F%40id%29&context=%2F%2Ftip%5B1%5D)

**Comment by DrRataplan** [comment]
Thanks! fixed at the playground (which is not open source due to the UI framework used there.)

Turned out to be a wrong implementation of `DomFacade#getData`. We expect it to return the value of attributes, which it did not.
