### ISSUE TITLE
Urn namespaces

### ISSUE THREAD

**Issue by kyrylkov** [FontoXML/fontoxpath#281]
How do we query `platformCore:webservicesDomain` from the XML below.  Because in [Fonto XPath Playground](https://xpath.playground.fontoxml.com/) we get the following error:

```
1: //platformCore:webservicesDomain
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: XPST0081: The prefix platformCore could not be resolved.
  at <pathExpr>:1:1 - 1:33
```

    <soapenv:Body>
        <getDataCenterUrlsResponse
            xmlns="urn:messages_2020_2.platform.webservices.com">
            <platformCore:getDataCenterUrlsResult
                xmlns:platformCore="urn:core_2020_2.platform.webservices.com">
                <platformCore:status isSuccess="true"/>
                <platformCore:dataCenterUrls>
                    <platformCore:webservicesDomain>https://1234567.site.com</platformCore:webservicesDomain>
                </platformCore:dataCenterUrls>
            </platformCore:getDataCenterUrlsResult>
        </getDataCenterUrlsResponse>
    </soapenv:Body>

**Comment by DrRataplan** [comment]
Hey there!

In the playground we try to resolve namespace prefixes to the document element that is being passed. That usually works out and is great for quickly running a query. For some scenarios however, that does not scale.

In XPath (as well as in all XML), prefixes are just syntactic sugar. Namespaces matter. There are two ways to make your query declare the namespace for your query. The easiest way is to pass a 'namespaceResolver' argument as an option. Roughly like

```
const namespaceBindings = {
  '': null,
  'platformCode': 'urn:core_2020_2.platform.webservices.com'
};

evaluateXPathToNodes(
  'descendant-or-self::platformCore:webservicesDomain', // Query
  document, // Context
  null, // DomFacade (not used)
  {}, // Variables (not used)
  {
    namespaceResolver: prefix => namespaceBindings[prefix||''] || null
  }
);
```
(Note that you can use whatever you like as a prefix! There are only namespace checks, prefixes are just for humans!)

The other way is to drop prefixes altogether and use the `Q{}` syntax: `descendant-or-self::Q{'urn:core_2020_2.platform.webservices.com'}webservicesDomain`. This is usually better if you are generating code, but feel free to use it to be a bit more verbose.

I hope this helps you! Please drop a note if we can help you any further!

Regard,

Martin
