### ISSUE TITLE
This package does not with Create React App

### ISSUE THREAD

**Issue by DrRataplan** [FontoXML/fontoxpath#286]
Since the dependency on xspattern, this package is incompatible with Create React App. Reason for this is that xspattern publishes an `xspattern.mjs` file, on which Closure Compiler errors.

There is a workaround by using `create-react-app-rewired`.

To get this workaround to work, follow the following steps:

1. Install `create-react-app-rewired`
2. Create a `config-overrides-file.js` in the root of your repository with the following:
```
const { override } = require("customize-cra");

const supportMjs = () => (webpackConfig) => {
    webpackConfig.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto",
    });
    return webpackConfig;
};

module.exports = override(
    supportMjs()
);
```
4. Change the start/stop/eject scripts to use the `create-react-app-rewired` variants:
```
"scripts": {
-    "start": "react-scripts start",
-    "build": "react-scripts build",
-    "test": "react-scripts test",
+    "start": "react-app-rewired start",
+    "build": "react-app-rewired build",
+    "test": "react-app-rewired test",
     "eject": "react-scripts eject"
   },
```

There is already an issue on xspattern.js: https://github.com/bwrrp/xspattern.js/issues/18.

There is also an issue on create-react-app: https://github.com/facebook/create-react-app/issues/10356.

I will update this issue when anything changes.

**Comment by bwrrp** [comment]
I've just released xspattern 2.0.0 which renames the bundles to both use the .js extension. This release has no other changes. Could you try bumping the dependency version and confirm whether that resolves the problem with CRA?

**Comment by DrRataplan** [comment]
Just released 3.15.0 @EvadeHaas @wvbe could you check whether CRA eats FontoXPath and xspattern now?

**Comment by EvadeHaas** [comment]
I can confirm that this works for a tsdx app

**Comment by DrRataplan** [comment]
Yay! Thanks for the confirmation @EvadeHaas!  I'm closing this issue!
