### ISSUE TITLE
parseScript is returning an element not a document

### ISSUE THREAD

**Issue by ymor** [FontoXML/fontoxpath#329]
Hi,
I was looking at giving parseScript a whirl, but I seem to be getting the following: `XPDY0050: the root node of the context node is not a document node.` when trying to evaluate any xpath across the result.
I essentially just used the example in the code documentation:
https://runkit.com/embed/zysy5z2l4ypd  as you can see the result is an element.

https://runkit.com/embed/jpl1it1n517c for the error when trying to evaluate an xpath again the result.

Thanks.

(I'm willing to look further into this one, but just wanted to get it logged first)

**Comment by ymor** [comment]
After a brief look, I can't see a way of fixing this without it been a breaking change.  So maybe its worth just updating the documentation example to be something like the following: https://runkit.com/embed/ifqhe1p02k1f ?

**Comment by DrRataplan** [comment]
Hey there,

I find it cool that you're looking at the parseScript function! That error is indeed a mistake we made. Sorry for that. I don't think it's that useful for the system to insert the result of parseScript into the passed document for you, detached elements should be ok.

I'll go ahead and change the documentation to read something like `descendant::nameTest`. Thanks for pointing it out!
