### ISSUE TITLE
Enum ReturnType present in typings but not actually exported by bundle

### ISSUE THREAD

**Issue by bwrrp** [FontoXML/fontoxpath#386]
The enum ReturnType is declared in the .d.ts. However, this export is not actually present in the generated (ESM) bundle.

This seems to be caused by the code in build.js filtering out only functions and variables, while this is an enum, and apparently named "ReturnType_2" in the data there...

**Comment by DrRataplan** [comment]
Fix is tracked in #390

**Comment by DrRataplan** [comment]
Fixed in #390
