### ISSUE TITLE
Implicit context item dependency in functions

### ISSUE THREAD

**Issue by MTimmerije** [FontoXML/fontoxpath#430]
There are several functions in xpath (Such as `fn:name`) that implicitly behave as if they are passed a ContextItem as a parameter when they are called without a parameter (`fn:name()` is identical to `fn:name(.)`).
The codegen backend however assumes that if the contextItem is used (and that it therefore should inject it into the generated code), that it is explicitly present within the AST, which is not the case with these functions that use it implicitly. If it does not detect any context item expression within the AST, it will not inject it into the codegen code, which could lead to bugs.

For the time being, there is explicit handling for the `fn:name()` and `fn:local-name()` that do use it, but this might be a thing to consider for the future when more functions are being added.

**Comment by DrRataplan** [comment]
Not really sure what to do with this issue, but I cannot disagree to consider cleaning up concepts when implementing new functions in codegeneration. Closing this nonetheless.
