### ISSUE TITLE
Parameter names seem to clash with globals

### ISSUE THREAD

**Issue by rrthomas** [FontoXML/fontoxpath#436]
I had the following code in an XQuery module that I loaded with `registerXQueryModule`:

```
declare function ruth:root-relative-path($path as xs:string) as xs:string {
  string-join(($ruth:path, $path), '/')
};
```

I found that the function did not work properly, but renaming the parameter made it work:

```
declare function ruth:root-relative-path($zpath as xs:string) as xs:string {
  string-join(($ruth:path, $zpath), '/')
};
```

I'm sorry, I don't have time to make a minimal failing example at present, so feel free to ignore this issue until such time as I can!

**Comment by DrRataplan** [comment]
That sure looks odd. Just tried it out in [the playground](https://xpath.playground.fontoxml.com/?mode=1&variables=%7B%7D&xml=%3Cxml%3E%0A++%3Ctitle%3Expath.playground.fontoxml.com%3C%2Ftitle%3E%0A++%3Csummary%3EThis+is+a+learning+tool+for+XML%2C+XPath+and+XQuery.%3C%2Fsummary%3E%0A++%3Ctips%3E%0A++++%3Ctip+id%3D%27edit%27%3EYou+can+edit+everything+on+the+left%3C%2Ftip%3E%0A++++%3Ctip+id%3D%27examples%27%3EYou+can+access+more+examples+from+a+menu+in+the+top+right%3C%2Ftip%3E%0A++++%3Ctip+id%3D%27permalink%27%3EAnother+button+there+lets+you+share+your+test+using+an+URL%3C%2Ftip%3E%0A++%3C%2Ftips%3E%0A%3C%2Fxml%3E&xpath=declare+namespace+ruth+%3D+%22123%22%3B%0Adeclare+variable+%24ruth%3Apath+%3A%3D+%22ruth%3Apath%22%3B%0A%0Adeclare+function+ruth%3Aroot-relative-path%28%24path+as+xs%3Astring%29+as+xs%3Astring+%7B%0A++string-join%28%28%24ruth%3Apath%2C+%24path%29%2C+%27%2F%27%29%0A%7D%3B%0A%0Aruth%3Aroot-relative-path%28%27abc%27%29&context=), but it seems to work OK over there. This might have to do with the separate modules. Also when I declare new global variables, I saw no crashes.

You are using separate modules right? How are you importing them? By using the XQuery `import` statement, or by using the JavaScript API `moduleImports`?

**Comment by rrthomas** [comment]
I am using separate modules, and importing them with XQuery `import`. I didn't get any crashes, just incorrect values in variables.

**Comment by DrRataplan** [comment]
Hey there,

I gave this a whirl and I can not reproduce this issue (anymore). I tried to reproduce it like this:

```
	it.only('repro', () => {
		registerXQueryModule(`
module namespace ruth = "http://www.example.com";

declare variable $ruth:path := "vrot";

declare function ruth:root-relative-path($path as xs:string) as xs:string {
  string-join(($ruth:path, $path), '/')
};`);

		chai.assert.equal(
			evaluateXPathToString(
				`import module namespace ruth="http://www.example.com";

ruth:root-relative-path("prrt")`,
				null,
				null,
				null,
				{ language: Language.XQUERY_3_1_LANGUAGE }
			),
			'vrot/prrt'
		);
	});
```

I'll close this issue for now, feel free to reopen it if you can still reproduce it.
