### ISSUE TITLE
Cannot work out how to call XQuery functions from TypeScript

### ISSUE THREAD

**Issue by rrthomas** [FontoXML/fontoxpath#443]
Consider the following code:

```typescript
import {evaluateXPathToString, registerCustomXPathFunction} from 'fontoxpath'

const foo = 'http://www.example.com/foo'
const URI_BY_PREFIX: {[key: string]: string} = {foo}

registerCustomXPathFunction(
  {localName: 'test', namespaceURI: foo},
  ['function(*)'], 'xs:string',
  (_, fn: () => string) => {
    console.log(`foo:test(${fn})`)
    const res = fn()
    console.log(res)
    return res
  },
)
const res = evaluateXPathToString(
  'foo:test(function () as xs:string { "abc" })',
  null,
  null,
  null,
  {
    namespaceResolver: (prefix: string) => URI_BY_PREFIX[prefix],
    debug: true,
  },
)
console.log(res)
```

I would expect the final line to print `abc`, but instead it prints `[object Object]`.

I am guessing that the problem is that I have not declared the function type more precisely: `function(*)` is an arbitrary function; but if I try to write `function (empty-sequence()) as xs:string` I get error XPST0081, which suggests that fontoxpath can't parse a `TypedFunctionTest` (as it's called in the XQuery grammar).

I can get the expected string value from `res.value.next().value.value`, but that doesn't seem robust or correct!

**Comment by rrthomas** [comment]
I have another problem, presumably related, when I try to pass an argument to an XQuery function from JavaScript. Consider the following modified version of the above code:

```typescript
import {evaluateXPathToString, registerCustomXPathFunction} from 'fontoxpath'

const foo = 'http://www.example.com/foo'
const URI_BY_PREFIX: {[key: string]: string} = {foo}

registerCustomXPathFunction(
  {localName: 'test', namespaceURI: foo},
  ['function(*)'], 'xs:string',
  (_, fn: (s: string) => string) => {
    console.log(`foo:test(${fn})`)
    const res: any = fn('abc')
    console.log(res.value.next().value.value)
    return res
  },
)
const res = evaluateXPathToString(
  'foo:test(function ($s as xs:string) as xs:string { $s })',
  null,
  null,
  null,
  {
    namespaceResolver: (prefix: string) => URI_BY_PREFIX[prefix],
    debug: true,
  },
)
console.log(res)
```

When I run this, I get the error:

```
Error: Custom XPath function Q{http://www.example.com/foo}test raised:
Cannot read property 'value' of undefined
    at Qc (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:75:546)
    at /home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:249:303
    at Array.reduce (<anonymous>)
    at value (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:249:275)
    at /home/rrt/Software/ruth/src/test.ts:11:22
    at hd.value (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:711:308)
    at /home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:197:201
    at Mk (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:195:141)
    at Nk.v (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:197:96)
    at Nk.Dk.evaluate (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:193:732)
  at <functionCallExpr>:1:1 - 1:57
    at new lm (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:233:30)
    at mm (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:234:67)
    at Ev (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:684:242)
    at Object.$y [as evaluateXPathToString] (/home/rrt/Software/ruth/node_modules/fontoxpath/dist/fontoxpath.js:686:1008)
    at Object.<anonymous> (/home/rrt/Software/ruth/src/test.ts:16:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/home/rrt/Software/ruth/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/home/rrt/Software/ruth/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  position: {
    end: { da: 57, line: 1, offset: 56 },
    start: { da: 1, line: 1, offset: 0 }
  }
}
```

I presume the problem here is that the JavaScript function implementing the anonymous XQuery function does not in fact take a string.

**Comment by DrRataplan** [comment]
Oh no, this is absolutely not something we have accounted for in the past! You are officially the first one who passes an XQuery _function_ as an argument to a function defined in JavaScript, congratulations! :tada: We're definitely going to need some type-marshalling to make this work! Indeed, the return value does not make sense: it should return an array of values (or something akin to that), passing arguments is going to take some work as well. Nice challenge you found!

I am under a bit of time pressure regarding other things right now, but I'll try to see how this can actually be done concretely, or whether we can think of a workaround!

Again, congrats on pushing the boundary!

**Comment by DrRataplan** [comment]
To properly implement this, we should implement function conversion in https://github.com/FontoXML/fontoxpath/blob/master/src/expressions/adaptJavaScriptValueToXPathValue.ts. Whenever we get a function in a sequence, wrap it in another function that (when called) does the standard type conversion we use in normal `evaluateXPath` to call it, and convert the return value using the algorithm already used to convert arguments to external functions, so null or a convertible value (aka recurse the algorithm so we can have functions that return functions). We should be able to get the type information for said function, so that we can have a predictable return type: a function annotated with `as item()*` returns an array of 'things', a function `as xs:string?` either null or a single string.

For now, as a workaround, you could consider calling the functions before passing them to the custom function. Since XQuery is supposed to be functional and pure, there should be no side-effects and calling the function _should_ be possible. Assuming the function you're passing is pure and won't throw errors of course.

I think this could be a wonderful addition to FontoXPath! Thanks again for finding the boundary and stepping over it!

Kind regards,

Martin

**Comment by rrthomas** [comment]
Thanks for looking into this, and for the suggested workaround.

**Comment by DrRataplan** [comment]
I'll close this for now because the discussion has paused.
