### ISSUE TITLE
array { random-number-generator()?permute(1 to 20) } gives array with only one member, should have twenty members

### ISSUE THREAD

**Issue by martin-honnen** [FontoXML/fontoxpath#498]
For the expression `array { random-number-generator()?permute(1 to 20) }` I expect an array of 20 integers, somehow FontoXml returns an array with only one integer, at least in the playground https://xpath.playground.fontoxml.com/?state=H4sIAOGFoGIAAzXMUQqCUBBG4a1c5klBKXsUqTUEbWDMIQLnTvzODeXi3tPAtwMHvkxqg1DbVPRlvLkfZaKW8koVzTpu2cHMrw%2BZvDv9cz%2F3JFi2yQAvIQdwHEzrmLQX1C%2BJAnZDUd4%2BAk0uRRPcwuVchl1%2BWnSZ%2FVBo%2FQFijOYqhwAAAA%3D%3D.

**Comment by DrRataplan** [comment]
You are right, the permute function was wrongly implemented: it returned a random value instead of permuting the input. This is fixed in #500! Thanks for bringing this up!
