### ISSUE TITLE
Problem with fontoxpath.js in Browser since v25.0

### ISSUE THREAD

**Issue by Violante** [FontoXML/fontoxpath#556]
Since v25.0 and later, loading in browser a file like :

      <html>
          <head>
              <script src="https://cdn.jsdelivr.net/npm/fontoxpath@3.28.1/dist/fontoxpath.min.js"></script>
          </head>
          <body>
          </body>
      </html>

gives the error: 

fontoxpath.js:404 
Uncaught TypeError: Cannot read properties of undefined (reading 'or')
    at fontoxpath.js:404:213
    at fontoxpath.js:607:2
    at fontoxpath.js:11:21
    at fontoxpath.js:13:3

This works with:
<script src="https://cdn.jsdelivr.net/npm/fontoxpath@3.24.1/dist/fontoxpath.min.js"></script>

**Comment by DrRataplan** [comment]
Hello Violante,

That's because in version 3.25.0, we transitioned from a parser based on PEG.js to a parser based on [prsc.js](https://github.com/bwrrp/prsc.js). This needs to be loaded as well to make the engine work.
Unfortunately, the CDN you are using does not allow loading the `umd` bundle from prsc. At least, the following did not work:      `<script src="https://cdn.jsdelivr.net/npm/prsc@4.0.0/dist/prsc.umd.cjs" ></script>`.

Just wondering, why are you not using a package manager like NPM to handle your dependencies? That seems more stable.

Alternatively, the `jsdelivr` CDN also offers esm bundles, but you will not be able to read `fontoxpath` from `window`, but you will have to do something like this:

```html
  <html>
      <head>
          <script type="module">
          import {evaluateXPathToString} from 'https://cdn.jsdelivr.net/npm/fontoxpath/+esm';
          const resultPre = window.document.getElementById('result');
          resultPre.innerText = evaluateXPathToString('fontoxpath:version()');
          </script>
      </head>
      <body>
      <pre id="result"/>
      </body>
  </html>
```

Hope this helps!

**Comment by Violante** [comment]
Thank you for your answer.

Indeed your suggestion with jsdeliver works.

I use in fact NPM but for a use with "node.js" + "puppeteer"

As I can't do a require('fontoxpath') and use fontxpath in the page.evaluate, I try to do otherwise.

Create a small HTML bootstrap that takes care of loading fontoxpath in the page.

await page.goto('./mybootstrap.html', {waitUntil: 'networkidle2'}).catch(e => console.error(e));

and then :

await page.evaluate(async () => {
    const content = await window.readfile('testfontoxpath.html');
	const parser = new DOMParser();
	const doc = parser.parseFromString(content, "text/xml");
	const s = new XMLSerializer();

    // start using fontoxpath here
 	console.log(evaluateXPathToString('fontoxpath:version()'));
	
}

Unfortunately, using 

<script type="module">
          import {evaluateXPathToString} from 'https://cdn.jsdelivr.net/npm/fontoxpath/+esm';
</script>

the object evaluateXPathToString remains unknown in page.evaluate.

The problem with the module approach will remain CORS as I would like everything to work locally.

Translated with www.DeepL.com/Translator (free version)

**Comment by DrRataplan** [comment]
Hello Violante,

Have you tried importing `fontoxpath` in the bootstrap page, at the start of the inlined script, or if it is a separate file, there? Just by adding `import {evaluateXPathToString} from 'https://cdn.jsdelivr.net/npm/fontoxpath/+esm';` at the start, in the same file as the `page.evaluate`? Also, if I recall correctly, puppeteer allows runtime dependencies that you can just inject from NPM.

**Comment by Violante** [comment]
Hello, I tried to load "fontoxpath" in the HTML bootstrap file with import {evaluateXPathToString} from 'https://cdn.jsdelivr.net/npm/fontoxpath/+esm'.
The import works and the "evaluateXPathToString" object is available in the <script> tag of the bootstrap.
However, contrary to what one might have expected, it remains undefined in puppeteer's page.evaluate{}.
I admit that I'm a bit confused...
Best regards
André

De : Martin Middel ***@***.***>
Envoyé : mardi 8 novembre 2022 13:32
À : FontoXML/fontoxpath ***@***.***>
Cc : Violante ***@***.***>; State change ***@***.***>
Objet : Re: [FontoXML/fontoxpath] Problem with fontoxpath.js in Browser since v25.0 (Issue #556)


Hello Violante,

Have you tried importing fontoxpath in the bootstrap page, at the start of the inlined script, or if it is a separate file, there? Just by adding import {evaluateXPathToString} from 'https://cdn.jsdelivr.net/npm/fontoxpath/+esm'; at the start, in the same file as the page.evaluate? Also, if I recall correctly, puppeteer allows runtime dependencies that you can just inject from NPM.

-
