### ISSUE TITLE
Simple map operator does not work on arrays

### ISSUE THREAD

**Issue by mvanbutselaar** [FontoXML/fontoxpath#59]
When using the simple map operator on arrays, the result is invalid. Doing so in the xpath playground returns the source code of the specified function as string in an array.

Steps to reproduce:
`["test"]!string()`

Result:
`["function(t,n,r,o){return zt(t,n,r,Ot(e),o)}"]`

Expected result:
`["test"]`

**Comment by DrRataplan** [comment]
Good find! The code here should behave equal to `["test"]!string(.)` (pay attention to the `.`), which unfortunately throws an error at this point. We actually do not support array atomization (array() => sequence of (atomized) contents => stringification) yet, but this is an extra dirty error. 

We should really implement array atomization, but that's another issue imho. I'll try to pick this up some time this week or next week.
