### ISSUE TITLE
Inconsistent behaviour across browsers (Chrome / Firefox)

### ISSUE THREAD

**Issue by ilariaschinina** [FontoXML/fontoxpath#605]
I am using fontoxpath in a project and noticed some inconsistent behaviors between Chrome and Firefox.
On Chrome the queries `//div` and `//*[name()='div']` find and match all the divs in the document. 
On Firefox, fontoxpath with the very simple query `//div`,  returns an empty array, while with the more convoluted query `//*[name()='div']` matches the divs.

I built a small project where the issue can be reproduced, you can find more details about the issue in the README and test yourself:
https://github.com/ilariaschinina/fontoxpath-test-project

Let me know if I can provide further details or clarifications.
 
Best,
Ilaria

**Comment by bwrrp** [comment]
It looks like Firefox' behavior is wrong in this case compared to the DOM spec. There's a 9 years old bug open for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1061578

**Comment by ilariaschinina** [comment]
Hello Martin,
thanks for the detailed answer and for suggesting a solution.
Passing a namespace resolver does the job :+1: 

Best,
Ilaria
