### ISSUE TITLE
Exceptions no longer stringify

### ISSUE THREAD

**Issue by rrthomas** [FontoXML/fontoxpath#628]
In past versions of fontoxpath, exceptions would stringify to the error message. This seems no longer to be the case; they just give the dreaded `[object Object]`.

I can recover the error message by printing `error.h` (in version 3.30.2), but that's fragile and depends on the minification of the exception object.

**Comment by rrthomas** [comment]
Further, if running with `DEBUG=yes`, the error message in traceback just becomes the rather obscure `#<Mh>` :)

**Comment by bwrrp** [comment]
Hi, I'm unfortunately not able to reproduce this using the following code (in a new node.js project with fontoxpath 3.30.2):
  
```js
const f = require('fontoxpath');
let e = null;
try {
	f.evaluateXPathToBoolean('fn:error("test")', null);
} catch (err) {
	e = err;
}

console.log({
	stringified: e.toString(),
	message: e.message,
	instanceOfError: e instanceof Error
});
```

Results in:
```js
{
  stringified: 'Error: XPTY0004 Unable to cast argument of type xs:string to type xs:QName? while calling error',
  message: 'XPTY0004 Unable to cast argument of type xs:string to type xs:QName? while calling error',
  instanceOfError: true
}
```

Perhaps you have a minifier on your end that's causing trouble here?

**Comment by rrthomas** [comment]
I'm not using a minifier as far as I know (plain TypeScript compilation in a Node project). I've not changed anything in my build system since it last worked.

**Comment by bwrrp** [comment]
Hmm, that seems to correspond to the internal `StackTraceEntry` class, which is supposed to remain internal as it should be caught and converted to a proper error. It seems we might have missed a spot there. Are you able to provide more details on the specific API / XPath being used here (or maybe even a stack trace?) to help track down where we missed a catch?

**Comment by rrthomas** [comment]
Sure! Will see what I can do. I have confirmed that if I run identical code with 3.30.2 and 3.28.2 then the serialization works with 3.28.2 but not 3.30.2. I'll see if I can get a backtrace now.

**Comment by rrthomas** [comment]
Is this what you're after, or did you want a stack trace inside fontoxpath?

```
(node:845631) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
error expanding 'incorrect.ruth.xml': Error: 1: <dirtree:file xmlns:dirtree="https://github.com/rrthomas/ruth/raw/main/dirtree.dtd" dirtree:path="incorrect.ruth.xml" dirtree:name="incorrect.ruth.xml">{foo()}
                                                                                                                                                            ^^^^^
2: </dirtree:file>

Error: XPST0017: Function Q{http://www.w3.org/2005/xpath-functions}foo with arity of 0 not registered. No similar functions found.
  at <functionCallExpr>:1:154 - 1:159
  at <elementConstructor>:1:1 - 2:16
file:///home/rrt/Software/ruth/src/index.ts:322
            throw new Error('there were errors during XQuery processing');
                  ^

Error: there were errors during XQuery processing
    at Expander.expand (file:///home/rrt/Software/ruth/src/index.ts:322:19)
    at file:///home/rrt/Software/ruth/src/cli.ts:36:36
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
```

**Comment by bwrrp** [comment]
Aha, thanks for that! It looks like `registerXQueryModule` is missing a catch-and-rethrow around its attempt to parse the input.
