### ISSUE TITLE
`XPTY0004: Multiplicity of function argument of type xs:string? for starts-with is incorrect. Expected "?", but got "+".` error when passing `.//text()` to function that takes a string

### ISSUE THREAD

**Issue by DetachHead** [FontoXML/fontoxpath#645]
the following xpath works in both chrome and firefox's xpath 1 implementation, but fails in fontoxpath:

```xpath
starts-with(.//text(), 'asdf')
```
```
Error: XPTY0004: Multiplicity of function argument of type xs:string? for starts-with is incorrect. Expected "?", but got "+".
  at <functionCallExpr>:1:1 - 1:31
```
[playground](https://xpath.playground.fontoxml.com/?state=H4sIAG%2FdqmYAA21Ry2rDMBD8lUUXJ%2BDaPQfX0HsKbWkhhV429joW1cNI69Qm5N%2B7tmtyaEGgkTQ7O6u5KOtrUrv7VJ0xaDwaimqnLleVqsEagYVs5acDKFizoXLokNusMziegu9dnTXesRdSVnlb5Atp5sfeWgxj%2BdbqCLIQDGFw2p2AvTfQ%2BACHp30Kh2eRBHQ1HF56CmNW5Gvtb%2BMuzmjBoOuHhGrNSfnhe6jQwXQCOkstt5O%2Bd8AtSb%2BGJ0vdn%2BoBbSej3hSwqihGsD4QrK%2FQBG%2FFtiXXg14k2XcQ9Kn9X7ejYNFo95WUj84LP8CxZ17siLIhjjBKy9iiHAUFYIoMfZxsi4%2F31%2F1NeUbT6EU%2BpTBlMn%2BQxBIZA8e7b83tJstzpoE32xQSjHWTbIVZSSxyufLV9QcTNjCx6wEAAA%3D%3D)

**Comment by DrRataplan** [comment]
Hey there,

Good question! Atomization is responsible for this behaviour: https://www.w3.org/TR/xpath-31/#id-atomization.

Step by step, this happens:

1. The function is resolved and we see we want `xs:string?` as the first argument (https://www.w3.org/TR/xpath-functions-31/#func-starts-with)
2. We start evaluating the argument, we see we have two or more nodes
3. We start atomizing those nodes, we get at least two strings
4. We see this cannot fit into the xs:string? argument, which accepts sequences with length one or zero.
5. We throw the corresponding error.

This is described in the spec here: https://www.w3.org/TR/xpath-31/#dt-function-conversion.

You will need to string-join here. 

In XPath 1.0 this works, like you observed. Technically you can reproduce this behaviour in XPath 3.1 with the use of the XPath 1.0 compatibility mode. This is not implemented and to be honest, I have no plans implementing this...

Kind regards,

Martin

**Comment by DetachHead** [comment]
thanks for the explanation

**Comment by DrRataplan** [comment]
No problem, my pleasure!
