### ISSUE TITLE
getBucketForSelector returns `null` for `(self::note)[@conref]`

### ISSUE THREAD

**Issue by DrRataplan** [FontoXML/fontoxpath#66]
Selector buckets can be used as a cheap pre-filtering for selectors. Fonto uses them extensively for all sorts of optimizations.

Unfortunately, it seems that the `(self::note)[@conref]` returns `null` as its bucket, indicating that it can match 'any' node.

This is wrong. This is likely caused by the XQueryX refactoring.

**Comment by DrRataplan** [comment]
BTW: failing test:

```
	it.only('returns the correct bucket for filter expressions', () => {
		chai.assert.equal(getBucketForSelector('(self::someElement)[@type="whatever"]'), 'name-someElement');
	});
```

**Comment by JosVerburg** [comment]
Issue was caused by the name test being wrapped in a sequence expression. We now no longer wrap a single expression in a sequence expression. This resolves this issue.
