### ISSUE TITLE
Support for IF conditions

### ISSUE THREAD

**Issue by MkuuWaUjinga** [FontoXML/fontoxpath#665]
Hi there,

if I'm not mistaken the XPath 3.1 spec supports IF conditions in the format `if (condition) then expression1 else expression2` or `if(condition, true-value, false-value)`. I tried XPaths like `//span[@id='MainContent_rbIsUsResident']/input[@value=if($variable='<value>') then '1' else '0']` with fontoxpath and they don't seem to evaluate. Is it possible that this is not supported yet? If not, I'd love pointers to files in your codebase so that I can add a PR with this functionality

**Comment by DrRataplan** [comment]
Hey Adrian,

We definitely have if conditions! I prepared a playground where it's working [here](https://xpath.playground.fontoxml.com/?state=H4sIAA3RJWcAA22RT2vDMAzFv4rwJS2UZOeShu3ewTY26Nh2cBOlMfOfYMslofS7T04WetggkGcs%2Fd6TdRHGNSi2dxtxll7Jo8YgtuJyFRsxGM2y5F%2F1aQFKUqSxGnpJXd5rOZ68i7bJW2fJcVFeO1MWc9FUH6Ix0o%2FVa6cC8CdBo%2FRW2ROQcxpa5%2BHwuN%2FA4YmRIG0Dh%2BeIfszLYun9Ne7DpGYNqtll2CjKqncXoZYW0gnwzL3UJb6zQB2yX0spUv%2Bne5Cm51FvBFnXGAIY5xGWW2i9MxzboI2gZiS5Hrw6df9ze%2FRGamW%2Fs%2BrBOq73cIxEcxwma6QAI1uGTvKRlQfCQBBDis053l72N%2FKk0uhlkbaQdjI9EK%2BlSFcf92y6Ui2sMpntsvIsdcQqWyc3C%2FMbAeqArJeJ11%2BMqXlnONACE9cfkoSsXQgCAAA%3D).

Operator precedence required me to wrap the thing in `()` though, did you try that?

Martin

**Comment by MkuuWaUjinga** [comment]
Wrapping in `()` works. Thanks for helping out!
